"""Paths, constants, persisted settings, and the two pipeline exceptions."""

from __future__ import annotations

import json
import os
from pathlib import Path

HERE = Path(__file__).parent
WEB_DIR = HERE / "web"

# Shipped, not fetched. Without a VAD model every transcript comes back with
# invented timestamps — measured, the same eleven-second spans that started all
# this — and nothing about the result says so. It is 864 KB beside a model the
# user already downloads in gigabytes, and settings used to hand them a curl
# command to run by hand for it. See docs/PIPELINE.md.
BUNDLED_VAD = HERE / "mac" / "models" / "ggml-silero-v5.1.2.bin"

# What this app can say about a transcription model, and where to get one.
# Generated by tools/gen_models.py — see the note at the top of it about why
# the sizes and hashes in it are not written by hand.
CATALOGUE = HERE / "models.json"


def vad_model() -> str:
    """The VAD model to use: whatever was chosen, else the one we ship."""
    chosen = settings().get("vad_model_path", "")
    if chosen and Path(chosen).expanduser().is_file():
        return str(Path(chosen).expanduser())
    return str(BUNDLED_VAD) if BUNDLED_VAD.is_file() else ""
_CHOSEN_DIR = os.environ.get("RESCRIBE_DATA_DIR")
DATA_DIR = Path(_CHOSEN_DIR or Path.home() / ".rescribe")

# The app was called Local Whisper Transcriber until the rename. Somebody who used it
# then has their settings, history and library under the old name; move them once — but
# only into the default location. A directory somebody named themselves is theirs alone.
# ponytail: delete this after a release or two — it only ever matters on first launch.
_OLD_DIR = Path.home() / ".local-whisper-transcriber"
if not _CHOSEN_DIR and not DATA_DIR.exists() and _OLD_DIR.is_dir():
    try:
        _OLD_DIR.rename(DATA_DIR)
    except OSError:
        pass  # a leftover old directory is not worth failing to start over

WORK_DIR = DATA_DIR / "work"
HISTORY = DATA_DIR / "history.jsonl"
SETTINGS = DATA_DIR / "settings.json"

BINARIES = ("ffmpeg", "ffprobe", "whisper-cli")
DEFAULT_EXTRA = "--temperature 0 --entropy-thold 3.0 --max-context 64"

# What a watched folder will pick up. Anything ffmpeg reads works when chosen by
# hand; this narrower list is what we are willing to transcribe unattended.
AUDIO_EXTS = (".m4a", ".mp3", ".wav", ".aac", ".flac", ".ogg")
VIDEO_EXTS = (".mp4", ".mov", ".webm", ".mkv")
MEDIA_EXTS = AUDIO_EXTS + VIDEO_EXTS

TRANSCRIPT_SUFFIX = "-transcript"

# Scratch directories for recordings are named so they can be told apart from
# job directories, which the sweep treats far less gently. Lives here because
# both the recorder and the sweep need it and neither may import the other.
RECORDING_PREFIX = "rec-"

# How much of a recording's own log is kept. Here for the same reason as the
# line above: the recorder writes it and the orphan reader rebuilds it, and
# neither of those two files may import the other.
MAX_LOG = 120

# Recording defaults. Every one of them is a Settings field.
RECORD_FOLDER = Path.home() / "Recordings"
RECORD_MAX_MINUTES = 180
RECORD_LABELS = ("Me", "Them")
RECORD_MAX_MINUTES_CEILING = 12 * 60

# How many recordings to keep. Zero means all of them, and is the default: see the
# note at the top of retention.py about why this one is not on out of the box.
RECORD_KEEP = 0
RECORD_KEEP_CEILING = 500


def recording_config() -> dict:
    """The recording settings, resolved, with every value usable as it stands."""
    conf = settings()
    folder = (conf.get("recording_folder") or "").strip()
    try:
        minutes = max(1, min(int(conf.get("record_max_minutes") or RECORD_MAX_MINUTES),
                             RECORD_MAX_MINUTES_CEILING))
    except (TypeError, ValueError):
        minutes = RECORD_MAX_MINUTES
    labels = ((conf.get("record_label_voice") or "").strip() or RECORD_LABELS[0],
              (conf.get("record_label_computer") or "").strip() or RECORD_LABELS[1])
    try:
        keep = max(0, min(int(conf.get("record_keep") or 0), RECORD_KEEP_CEILING))
    except (TypeError, ValueError):
        keep = RECORD_KEEP
    return {
        "folder": str(Path(folder).expanduser()) if folder else str(RECORD_FOLDER),
        "voice": conf.get("record_voice_device") or "",
        "computer": conf.get("record_computer_device") or "",
        "labels": labels,
        # Off unless explicitly turned on. Transcribing is the expensive half and
        # the moment a meeting ends is often the worst time to spend a machine on
        # it; the recording is safe on disk either way and the Library will
        # transcribe it whenever asked. This was on by default once, which meant a
        # long recording seized the machine the instant it was saved.
        "transcribe": conf.get("record_auto_transcribe") is True,
        "max_seconds": minutes * 60,
        "max_minutes": minutes,
        "keep": keep,
    }


def source_folders() -> list[str]:
    """Folders to look in for new recordings. `watch_folders` was the old name."""
    conf = settings()
    return conf.get("source_folders") or conf.get("watch_folders") or []


class Failed(Exception):
    def __init__(self, code: str, message: str, pane: str = ""):
        super().__init__(message)
        # `pane` names a macOS privacy pane to offer to open. Naming the pane in a
        # sentence is not the same as getting somebody to it, and the difference is
        # a person hunting through System Settings while a meeting starts.
        self.code, self.message, self.pane = code, message, pane


class Cancelled(Exception):
    pass


def settings() -> dict:
    """Everything that was saved, or as much of it as can still be read.

    A file that will not parse used to come back as {} — and the next save merged
    onto that nothing and wrote it out, so a single bad byte plus one visit to
    settings destroyed the lot: model, folders, devices, labels, tool paths, in
    silence. Nothing announced it and nothing could get it back.

    So a broken file is salvaged rather than abandoned. Whatever can be read out of
    it is kept, key by key; only the part that will not parse is lost.
    """
    try:
        raw = SETTINGS.read_text(encoding="utf-8")
    except OSError:
        return {}
    try:
        return json.loads(raw)
    except ValueError:
        return _salvage(raw)


def _salvage(raw: str) -> dict:
    """As many whole `"key": value` pairs as survive in a file that will not parse.

    A truncated write leaves a prefix of good JSON, which is the usual way this
    happens, so parsing the longest valid prefix recovers nearly all of it.
    """
    for end in range(len(raw), 1, -1):
        if raw[end - 1] not in ",{ \t\r\n":
            continue
        try:
            found = json.loads(raw[:end].rstrip().rstrip(",") + "}")
        except ValueError:
            continue
        if isinstance(found, dict):
            return found
    return {}


def save_settings(values: dict) -> dict:
    """Persist the values given, leaving anything not mentioned untouched.

    An empty string is a real value here — it is how a field is cleared. Callers
    must send only the keys they mean to change (see the route's exclude_unset),
    or a partial save would wipe everything it left out.
    """
    merged = settings() | values
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    # Written beside and moved into place, because writing over the file is what
    # produces the half-file in the first place: a crash or a full disk in the
    # middle of a truncating write leaves exactly the wreckage above.
    spare = SETTINGS.with_suffix(".json.new")
    spare.write_text(json.dumps(merged, indent=2), encoding="utf-8")
    os.replace(spare, SETTINGS)
    return merged
